# Generated by Django 2.0.7 on 2018-08-21 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(13)]),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(13)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='avg_mark',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
