# Generated by Django 2.0.7 on 2018-09-11 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_auto_20180831_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='clas',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='clas',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='university.Clas'),
            preserve_default=False,
        ),
    ]
